# Generated by Django 5.2 on 2025-04-10 13:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_comment_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follow',
            new_name='Follower',
        ),
        migrations.AlterUniqueTogether(
            name='follower',
            unique_together=set(),
        ),
    ]
