# Generated by Django 5.2 on 2025-04-11 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_message_delete_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
